### ISSUE TITLE
Anchor links in header should scroll to content or be removed

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/tpc#17]
http://localhost:8080/#start-small
http://localhost:8080/#finish-big
http://localhost:8080/#stay-finished
http://localhost:8080/#supports-your-decisions
http://localhost:8080/#artisans

**Comment by blaflamme** [comment]
removed for now https://github.com/Pylons/tpc/commit/023c5970e284d5212c449bc4196876b449bcc626
