### ISSUE TITLE
Convert bold text to links

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/tpc#18]
I assume that the bold text under Start Small / Finish Big / Stay Finished in the bulleted list items is intended to be converted to links to the documentation and other existing assets.

If that is not the intent, then please close this issue.

**Comment by blaflamme** [comment]
I don't think that was the intent but we probably can put links in there if it makes sense.

**Comment by blaflamme** [comment]
In fact the idea of bolding those texts was to make you focus on the important content while you're screening the page and content.

**Comment by pauleveritt** [comment]
I think Steve is right on the intent. It was supposed to scroll to the internal link.

—Paul

**Comment by stevepiercy** [comment]
@pauleveritt I meant not the links in the header, but for each bold text item in the content in the sections below. Not a scroll to, but a `<a href="http://docs.pylonsproject.org/projects/pyramid/en/latest/" target="_blank">Pyramid Documentation</a>`, as an example.

**Comment by blaflamme** [comment]
@stevepiercy @pauleveritt the intent was to highlight features as I said before. Lets see if we do some linking in the future but not now.

**Comment by stevepiercy** [comment]
I set this item for milestone 0.2. Feel free to change that, or close this issue if y'all are certain that the bolded features should not be links instead.

**Comment by bertjwregeer** [comment]
One of my first reactions when reading that page was to attempt to click the bolded "single-file module", same with "high-quality add-ons" and "form systems".

**Comment by pauleveritt** [comment]
I think linkification is something we’ll work on this week for 0.2, which is the version that we hope to announce.

—Paul

**Comment by blaflamme** [comment]
sure that's a great idea, but it serves a different purpose. The boldish approach is to help reader focus on features that could not have any related links. so I think we should not mix both together. Once we start adding links, they have a different color, we should remove boldish words.

**Comment by blaflamme** [comment]
After looking at the entry page and thinking about it, I think we shouldn't convert those into links, and refer to the resource page where its purpose will be exactly to link to external resources.

**Comment by stevepiercy** [comment]
Closing per @blaflamme https://github.com/Pylons/tpc/issues/18#issuecomment-94557650
