### ISSUE TITLE
Change icon to represent "Stay Finished"

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/tpc#19]
The "puzzle piece" icon does not represent being finished to me. Suggest glyphicons-beer, glyphicons-cup, or glyphicons-circle-ok.

**Comment by blaflamme** [comment]
@stevepiercy @pauleveritt it's hard to find a good icon for this... the stay finished not just mean **done** but also as you grow and continue developing, you stay in a finish state.

look in font-awesome set

**Comment by blaflamme** [comment]
can be thumbs up?

http://fontawesome.io/icon/thumbs-up/

**Comment by stevepiercy** [comment]
Thumbs up looks too much like the Facebook "Like".

**Comment by blaflamme** [comment]
the check?

http://fontawesome.io/icon/check/

**Comment by blaflamme** [comment]
http://fontawesome.io/icon/beer/
http://fontawesome.io/icon/coffee/
http://fontawesome.io/icon/road/
http://fontawesome.io/icon/trophy/

**Comment by stevepiercy** [comment]
Check is OK, but Trophy has more symbolic meaning and looks slightly better. You win a trophy at the finish.

I prefer the glyphicon version to fontawesome, but not at the expense of yet another icon library.

**Comment by blaflamme** [comment]
use trophy https://github.com/Pylons/tpc/commit/d07c6cacb8937ea43113c30f83a76940ddcfeabc

**Comment by stevepiercy** [comment]
We have a winnaaaahhhh! :trophy:
