### ISSUE TITLE
Set up web stats, tracking, Google Analytics, etc.

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/tpc#4]
I propose setting up whatever standard stats and tracking stuff we use on pylonsproject.org including the following.

* Google Webmaster Tools
* Google Analytics
* website statistics on the server
* other?

**Comment by blaflamme** [comment]
All the Google stuff is good enough I think.

**Comment by pauleveritt** [comment]
> On Apr 15, 2015, at 3:30 PM, Steve Piercy <notifications@github.com> wrote:
> 
> I propose setting up whatever standard stats and tracking stuff we use on pylonsproject.org including the following.
> 
> Google Webmaster Tools
> Google Analytics

+1

**Comment by mmerickel** [comment]
Who owns the GA account? Can I get added to the webmaster tools and GA?

**Comment by blaflamme** [comment]
@mmerickel send me your email and I'll add you

**Comment by mmerickel** [comment]
My gmail address is in all my mailing list posts!

**Comment by blaflamme** [comment]
I think I don’t have it?

I have michael@merickel.org <mailto:michael@merrickel.org>

**Comment by mmerickel** [comment]
It's mmericke@gmail.com

**Comment by blaflamme** [comment]
you’ve been added

**Comment by stevepiercy** [comment]
@blaflamme Once the new trypyramid.com is deployed, please ping me, and I will poke our GA account to recognize GWT.

**Comment by blaflamme** [comment]
@stevepiercy ok

**Comment by blaflamme** [comment]
v0.1.0 is online

**Comment by stevepiercy** [comment]
Added all users from GA to GWT for trypyramid.com. This is now done. Closing.
