### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by pauleveritt** [Pylons/tpc#7]
Don't have one, need one. Existing trypyramid.com doesn't have one, so putting this in 0.2.

Blaise, if there's already a favicon.ico in one of the scaffolds/themes, re-assign to me and I'll get it into this.

**Comment by blaflamme** [comment]
@pauleveritt if new scaffold hasn't one, upc-wip should have one

**Comment by stevepiercy** [comment]
There are a series of touch and favicons for the current trypyramid.com. See the repo.
https://github.com/Pylons/trypyramid/blob/master/index.html

They probably need updating, too. To generate them, I used this lovely tool, inspired by Audrey Roy.
https://github.com/dropkick/automagical-icon-maker

**Comment by blaflamme** [comment]
@stevepiercy here they look crispy, so the export was not enough good it appears.

**Comment by pauleveritt** [comment]
“Awesomely crisp favicons” is not on my agenda. :) I’ll take what Steve has done and move it over. Then later, if Blaise can’t tolerate it, he can update it.

—Paul

**Comment by stevepiercy** [comment]
I have a .psd with a PNG of the Pyramid logo in it, but I don't want to commit it to a repo because of its large file size. I'll email a .zip to Paul now.

**Comment by blaflamme** [comment]
@stevepiercy I have all the originals from the artist including vector ones. Would be better to start off those. Please don't put original files publicly as is, we'll find a way to make them available to the public with the right licence and how to use them.

**Comment by mmerickel** [comment]
Maybe just make a `tpc-artwork` repo?

**Comment by mmerickel** [comment]
We also made https://github.com/Pylons/artwork at one point.

**Comment by pauleveritt** [comment]
Hmm, not sure what I should do at this point. Blaise, I’ll delete my branch and re-assign this ticket to you.

—Paul

**Comment by blaflamme** [comment]
@mmerickel that'd probably be a better place once we're ready to make them available.

**Comment by blaflamme** [comment]
@pauleveritt if you can make it look great I have no problems having you doing it :P

**Comment by blaflamme** [comment]
see the difference...
![screen shot 2015-04-16 at 12 10 23](https://cloud.githubusercontent.com/assets/454978/7185630/e2168292-e431-11e4-87ee-793552955cd9.png)
![screen shot 2015-04-16 at 12 11 56](https://cloud.githubusercontent.com/assets/454978/7185631/e221f60e-e431-11e4-8c7d-d58ac7f64a31.png)

**Comment by pauleveritt** [comment]
Based on conversation with Blaise, I went ahead and did a small PR for just a simple PNG favicon from the Pyramid scaffold. I will make a ticket post-0.2 for all the flavors of favicon.
